apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webby-data
  namespace: webby
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""  # leave blank to use cluster default
